# Generated by Django 3.2.5 on 2021-07-13 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Tag for your post', max_length=255),
        ),
    ]
