# Generated by Django 3.2.5 on 2021-07-16 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210716_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='udpated',
            field=models.DateField(auto_now_add=True),
        ),
    ]
