# Generated by Django 3.2.5 on 2021-08-14 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, default='static/ProyectoBlog/images/default-profile-pic.png', null=True, upload_to='bios'),
        ),
    ]
