# Generated by Django 3.2.5 on 2021-08-17 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_rename_image_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic',
            field=models.ImageField(blank=True, default='ProyectoBlog/images/default-profile-pic.png', null=True, upload_to='bios'),
        ),
    ]
