# Generated by Django 3.2.5 on 2021-08-20 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
